### ISSUE TITLE
Improve docs (misc)

### ISSUE THREAD

**Issue by tanertopal** [adap/flower#552]
# Description
Improve the docs by removing obsolete parts and making it overall more readable (also on mobile).

# Tasks
- [x] Remove obsolete parts of the docs aka. How To AWS
- [x] Fix formatting
- [x] Use new Theme
- [ ] Improve API Reference

**Comment by tanertopal** [comment]
Related PR's
* #547 
* #548 
* #551

**Comment by tanertopal** [comment]
Also relates to #551
